server:
  port: 8081

spring:
  application:
    name: cmb-question-bank-api

logging:
#  pattern.dateformat: yyyy-MM-dd HH:mm:ss.SSS
  level:
    root: INFO
    org.springframework.data.convert.CustomConversions: ERROR
---

# local
spring:
  config:
    activate:
      on-profile: local
  elasticsearch:
    rest:
      uris: http://di1shuai-2:9200

logging:
  file:
    path: logs

---
# dev
spring:
  config:
    activate:
      on-profile: dev
  elasticsearch:
    rest:
      uris: elasticsearch:9200

logging:
  file:
    path: /root/logs