server:
  port: 8081

spring:
  application:
    name: cmb-question-bank-api


---

# local
spring:
  config:
    activate:
      on-profile: local
  elasticsearch:
    rest:
      uris: di1shuai-2:9200

logging:
  file:
    path: logs

---
# dev
spring:
  config:
    activate:
      on-profile: dev
  elasticsearch:
    rest:
      uris: elasticsearch:9200

logging:
  file:
    path: /root/logs