server:
  port: 8081

spring:
  application:
    name: cmb-question-bank-api
  elasticsearch:
    rest:
      uris: di1shuai-2:9200


---

# local
spring:
  config:
    activate:
      on-profile: local

logging:
  file:
    path: logs

---
# dev
spring:
  config:
    activate:
      on-profile: dev

logging:
  file:
    path: logs