server:
  port: 8081

spring:
  elasticsearch:
    rest:
      uris: di1shuai-2:9200
---

# local
spring:
  config:
    activate:
      on-profile: local


---
# dev
spring:
  config:
    activate:
      on-profile: dev