name: Java Deploy with Maven

on:
  create:
    tags:
      - v*
    branches: [master]

jobs:
  build:
    env:
      DOCKER_PROJECT: cmb-question-bank-api 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: |
          mvn package -Dmaven.test.skip=true
      - name: Init Env
        run: |
          echo "DOCKER_VERSION=`docker images | grep $DOCKER_PROJECT | awk 'NR==1 {print $2}'`" >> $GITHUB_ENV
          echo "DOCKER_IMAGE_NAME=${{secrets.DOCKER_REGISTRY}}/${{secrets.DOCKER_ORGANIZTION}}/$DOCKER_PROJECT" >> $GITHUB_ENV
      - name: Push Docker
        run: |
          docker login -u ${{secrets.DOCKER_REGION}}@${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}} ${{secrets.DOCKER_REGISTRY}}
          docker images
          docker tag $DOCKER_PROJECT:$DOCKER_VERSION $DOCKER_IMAGE_NAME:$DOCKER_VERSION
          docker tag $DOCKER_IMAGE_NAME:$DOCKER_VERSION $DOCKER_IMAGE_NAME:latest
          docker images
          docker push $DOCKER_IMAGE_NAME:$DOCKER_VERSION
          docker push $DOCKER_IMAGE_NAME:latest

  pull-docker:
    env:
      DOCKER_PROJECT: cmb-question-bank-api   
    needs: [build]
    name: Pull Docker
    runs-on: ubuntu-latest
    steps:
      - name: Init Env 
        run: |
          echo "DOCKER_VERSION=`docker images | grep $DOCKER_PROJECT | awk 'NR==1 {print $2}'`" >> $GITHUB_ENV
          echo "DOCKER_IMAGE_NAME=${{secrets.DOCKER_REGISTRY}}/${{secrets.DOCKER_ORGANIZTION}}/$DOCKER_PROJECT" >> $GITHUB_ENV
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PWD }}
          port: ${{ secrets.PORT }}
          script: |
            docker ps
            docker stop $(docker ps --filter ancestor=$DOCKER_IMAGE_NAME -q)
            docker ps
            docker rm -f $(docker ps -a --filter ancestor=$DOCKER_IMAGE_NAME:latest -q)
            docker rmi -f $(docker images  $DOCKER_IMAGE_NAME:latest -q)
            docker images
            docker pull $DOCKER_IMAGE_NAME:latest
            docker images
            docker run --name $DOCKER_PROJECT:$DOCKER_VERSION -p 8081:8081 -d $DOCKER_IMAGE_NAME:latest
